---
dist: xenial
sudo: required
language: python
services:
  - docker
python: '3.7'

before_script:
  - cd ../
  - mv ansible-role-php daixijun.php
  - cd daixijun.php

install:
  - pip install ansible molecule docker
  - pip install --upgrade testinfra

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
