---
dist: xenial
sudo: required
language: python
services:
  - docker
python:
  - "3.7"
  - "3.8"

before_script:
  - cd ..
  - ln -sf ansible-role-php daixijun.php
  - cd daixijun.php

install:
  - pip install ansible "molecule[docker,lint]"
  - ansible --version
  - molecule --version

script:
  - molecule test

notifications:
  email: false
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
