---
sudo: required
language: python
services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-php daixijun.php
  - cd daixijun.php

install:
  - pip install ansible molecule docker

script:
  - travis_wait 60 molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
