---
- name: Verify php version
  fail:
    msg: "php_version must greater 7.0"
  when: php_version is version("7.0", operator="lt", strict=True)

- name: Verify that PHP is installed
  stat:
    path: /usr/local/php/bin/php
  register: php_installed_stat

- name: Get installed version
  raw: /usr/local/php/bin/php --version | head -1 | awk '{print $2}'
  register: php_installed_version
  changed_when: false
  when:
    - php_installed_stat.stat.exists
  tags:
    - skip_ansible_lint

# - name: Compare version
#   set_fact:
#     php_need_install: false
#   when:
#     - php_installed_stat.stat.exists
#     - php_installed_version is defined
#     - php_installed_version.stdout.strip() is version(php_version, operator="eq", strict=True)
#     - not php_force_install

- name: Remove installed same version
  file:
    path: /usr/local/php-{{ php_version }}
    state: absent
  when:
    - php_installed_stat.stat.exists
    - php_force_install
    - php_installed_version is defined
    - "'stdout' in php_installed_version"
    - php_installed_version.stdout.strip() is version(php_version, operator="eq", strict=True)
  tags:
    - skip_ansible_lint

- name: Message for PHP already installed
  debug:
    msg: "expected version {{ php_version }} but {{ php_installed_version.stdout.strip() }} already installed. set php_force_install parameter to force reinstall"  # noqa 204
  changed_when: true
  when:
    - php_installed_stat.stat.exists
    - not php_force_install
    - php_installed_version is defined
    - "'stdout' in php_installed_version"
    - not php_installed_version.stdout.strip() is version(php_version, operator="eq", strict=True)
