---
- name: Get extension directory
  command: /usr/local/php/bin/php-config --extension-dir
  register: get_extension_dir
  changed_when: false
  check_mode: no
  tags:
    - skip_ansible_lint

- name: Ensure facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    recurse: true

- name: Render php local fact
  template:
    src: local_facts.yaml.j2
    dest: /etc/ansible/facts.d/php.fact
