---
- name: Verify php version
  fail:
    msg: "php_version must greater 7.0"
  when: php_version is version("7.0", operator="lt", strict=True)

- name: Verify libzip version
  fail:
    msg: "Libzip version greater than 1.4 is not currently supported"
  when: php_libzip_version is version("1.4.0", operator=">=")

- name: Remove installed same version
  file:
    path: /usr/local/php-{{ php_version }}
    state: absent
  when:
    - php_force_install|bool
    - ansible_local.php.version is defined
    - ansible_local.php.version is version(php_version, operator="eq", strict=True)
  tags:
    - skip_ansible_lint

- name: Message for PHP already installed
  fail:
    msg: "expected version {{ php_version }} but {{ ansible_local.php.version }} already installed. set php_force_install=true parameter to force reinstall"
  when:
    # - php_installed_stat.stat.exists
    - not php_force_install
    - ansible_local.php.version is defined
    - not ansible_local.php.version is version(php_version, operator="eq", strict=True)

- name: Install dependencies
  package:
    name: "{{ php_dependencies }}"
    state: present
    update_cache: yes

- name: Ensure {{ php_web_user }} group exists
  group:
    name: "{{ php_web_user }}"
    system: yes
    state: present
  tags:
    - user

- name: Ensure {{ php_web_user }} user exists
  user:
    name: "{{ php_web_user }}"
    shell: /sbin/nologin
    home: /var/cache/nginx
    group: "{{ php_web_user }}"
    system: yes
    move_home: yes
    state: present
  tags:
    - user
