---
name: build
on: push
jobs:
  molecule:
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible "molecule[docker,lint]"
      - name: Test with molecule
        run: |
          cd ..
          ln -sf ansible-role-php daixijun.php
          cd daixijun.php
          molecule test
      - name: Publish role to Galaxy
        if: success()
        run: |
          ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
